title: Robin Sache
email: robinmeier758@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  An  accumulation of things ("sache" in swiss german) I have done and think are worth showing off.
  Some of it will be in german and some in english.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  robin-ny
# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-include-cache


defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: false
      related: true
